name: paysmartchallenge
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^7.3.3
  http: ^0.13.4
  rxdart: ^0.27.2
  connectivity: ^3.0.6
  logger: ^1.1.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.7
  

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

